# Generated by Django 5.0.3 on 2024-04-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_mlb', '0002_alter_team_info_league_short_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_info',
            name='Image',
            field=models.CharField(blank=True),
        ),
    ]
